
export default {
  server: {
    port: 8000, // default: 3000
    host: '0.0.0.0' // default: localhost
  },
  mode: 'universal',
  /*
  ** Headers of the page
  */
  head: {
    htmlAttrs: {
      lang: 'fr'
    },
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' },
      { name: 'msapplication-TileColor', content: process.env.theme_color || '#ffffff' },
      { name: 'theme-color', content: process.env.theme_color || '#ffffff' },

      { itemprop: 'name', content: 'Socobat Environnement' },
      { itemprop: 'description', content: 'Spécialiste du traitement des dechets, centre de tri et location de bennes' },
      { itemprop: 'image', content: 'https://socobat-environnement.netlify.com/social/share-1200x630.jpg' },

      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:title', content: 'Socobat Environnement' },
      { name: 'twitter:description', content: 'Spécialiste du traitement des dechets, centre de tri et location de bennes' },
      { name: 'twitter:image', content: 'https://socobat-environnement.netlify.com/social/share-1200x600.jpg' },

      { property: 'og:site_name', content: 'Socobat Environnement' },
      { property: 'og:type', content: 'website' },
      { property: 'og:url', content: 'https://socobat-environnement.netlify.com' },
      { property: 'og:title', content: 'Socobat Environnement' },
      { property: 'og:description', content: 'Spécialiste du traitement des dechets, centre de tri et location de bennes' },
      { property: 'og:image', content: 'https://socobat-environnement.netlify.com/social/share-1200x630.jpg' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: 'favicon/favicon.ico' },
      { rel: 'icon', type: 'image/png', href: 'favicon/favicon-32x32.png' },
      { rel: 'icon', type: 'image/png', href: 'favicon/favicon-16x16.png' },
      { rel: 'apple-touch-icon', sizes: '180x180', href: 'favicon/apple-touch-icon.png' },
      { rel: 'manifest', href: 'favicon/site.webmanifest' },
      { rel: 'mask-icon', href: 'favicon/safari-pinned-tab.svg', color: '#006633' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#3aaa35' },
  /*
  ** Global CSS
  */
  css: [
    '@/assets/style/common.styl'
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    { src: '~plugins/ga.js', mode: 'client' }
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/eslint-module',
    ['@nuxtjs/google-analytics', {
      id: 'UA-173950467-1'
    }]
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/proxy',
    '@nuxtjs/pwa',
    // Doc: https://github.com/nuxt-community/dotenv-module
    ['@nuxtjs/dotenv', { path: './' }],
    // Doc : https://github.com/nuxt-community/style-resources-module
    '@nuxtjs/style-resources'
  ],
  styleResources: {
    stylus: './assets/style/*.styl'
  },
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
    proxy: true,
    debug: true
  },
  proxy: {
    '/api/': {
      target: 'https://api.typeform.com/',
      pathRewrite: { '^/api/': '' }
    }
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  },
  generate: {
    routes: [
      '/Paris 1er Arrondissement',
      '/Paris 2e Arrondissement',
      '/Paris 3e Arrondissement',
      '/Paris 4e Arrondissement',
      '/Paris 5e Arrondissement',
      '/Paris 6e Arrondissement',
      '/Paris 7e Arrondissement',
      '/Paris 8e Arrondissement',
      '/Paris 9e Arrondissement',
      '/Paris 10e Arrondissement',
      '/Paris 11e Arrondissement',
      '/Paris 12e Arrondissement',
      '/Paris 13e Arrondissement',
      '/Paris 14e Arrondissement',
      '/Paris 15e Arrondissement',
      '/Paris 16e Arrondissement',
      '/Paris 17e Arrondissement',
      '/Paris 18e Arrondissement',
      '/Paris 19e Arrondissement',
      '/Paris 20e Arrondissement',
      '/Achères-la-Forêt',
      '/Amillis',
      '/Amponville',
      '/Andrezel',
      '/Annet-sur-Marne',
      '/Arbonne-la-Forêt',
      '/Argentières',
      '/Armentières-en-Brie',
      '/Arville',
      '/Aubepierre-Ozouer-le-Repos',
      '/Aufferville',
      '/Augers-en-Brie',
      '/Aulnoy',
      '/Avon',
      '/Baby',
      '/Bagneaux-sur-Loing',
      '/Bailly-Romainvilliers',
      '/Balloy',
      '/Bannost-Villegagnon',
      '/Barbey',
      '/Barbizon',
      '/Barcy',
      '/Bassevelle',
      '/Bazoches-lès-Bray',
      '/Beauchery-Saint-Martin',
      '/Beaumont-du-Gâtinais',
      '/Beautheil-Saints',
      '/Beauvoir',
      '/Bellot',
      '/Bernay-Vilbert',
      '/Beton-Bazoches',
      '/Bezalles',
      '/Blandy',
      '/Blennes',
      '/Bois-le-Roi',
      '/Boisdon',
      '/Boissettes',
      '/Boissise-la-Bertrand',
      '/Boissise-le-Roi',
      '/Boissy-aux-Cailles',
      '/Boissy-le-Châtel',
      '/Boitron',
      '/Bombon',
      '/Bougligny',
      '/Boulancourt',
      '/Bouleurs',
      '/Bourron-Marlotte',
      '/Boutigny',
      '/Bransles',
      '/Bray-sur-Seine',
      '/Bréau',
      '/Brie-Comte-Robert',
      '/Brou-sur-Chantereine',
      '/Burcy',
      '/Bussières',
      '/Bussy-Saint-Georges',
      '/Bussy-Saint-Martin',
      '/Buthiers',
      '/Cannes-Écluse',
      '/Carnetin',
      '/Cély',
      '/Cerneux',
      '/Cesson',
      '/Cessoy-en-Montois',
      '/Chailly-en-Bière',
      '/Chailly-en-Brie',
      '/Chaintreaux',
      '/Chalautre-la-Grande',
      '/Chalautre-la-Petite',
      '/Chalifert',
      '/Chalmaison',
      '/Chambry',
      '/Chamigny',
      '/Champagne-sur-Seine',
      '/Champcenest',
      '/Champdeuil',
      '/Champeaux',
      '/Champs-sur-Marne',
      '/Changis-sur-Marne',
      '/Chanteloup-en-Brie',
      '/Charmentray',
      '/Charny',
      '/Chartrettes',
      '/Chartronges',
      '/Château-Landon',
      '/Châteaubleau',
      '/Châtenay-sur-Seine',
      '/Châtenoy',
      '/Châtillon-la-Borde',
      '/Châtres',
      '/Chauconin-Neufmontiers',
      '/Chauffry',
      '/Chaumes-en-Brie',
      '/Chelles',
      '/Chenoise-Cucharmoy',
      '/Chenou',
      '/Chessy',
      '/Chevrainvilliers',
      '/Chevru',
      '/Chevry-Cossigny',
      '/Chevry-en-Sereine',
      '/Choisy-en-Brie',
      '/Citry',
      '/Claye-Souilly',
      '/Clos-Fontaine',
      '/Cocherel',
      '/Collégien',
      '/Combs-la-Ville',
      '/Compans',
      '/Conches-sur-Gondoire',
      '/Condé-Sainte-Libiaire',
      '/Congis-sur-Thérouanne',
      '/Coubert',
      '/Couilly-Pont-aux-Dames',
      '/Coulombs-en-Valois',
      '/Coulommes',
      '/Coulommiers',
      '/Coupvray',
      '/Courcelles-en-Bassée',
      '/Courchamp',
      '/Courpalay',
      '/Courquetaine',
      '/Courtacon',
      '/Courtomer',
      '/Courtry',
      '/Coutençon',
      '/Coutevroult',
      '/Crécy-la-Chapelle',
      '/Crégy-lès-Meaux',
      '/Crèvecœur-en-Brie',
      '/Crisenoy',
      '/Croissy-Beaubourg',
      '/Crouy-sur-Ourcq',
      '/Cuisy',
      '/Dagny',
      '/Dammarie-les-Lys',
      '/Dammartin-en-Goële',
      '/Dammartin-sur-Tigeaux',
      '/Dampmart',
      '/Darvault',
      '/Dhuisy',
      '/Diant',
      '/Donnemarie-Dontilly',
      '/Dormelles',
      '/Doue',
      '/Douy-la-Ramée',
      '/Échouboulains',
      '/Égligny',
      '/Égreville',
      '/Émerainville',
      '/Esbly',
      '/Esmans',
      '/Étrépilly',
      '/Everly',
      '/Évry-Grégy-sur-Yerre',
      '/Faremoutiers',
      '/Favières',
      '/Faÿ-lès-Nemours',
      '/Féricy',
      '/Férolles-Attilly',
      '/Ferrières-en-Brie',
      '/Flagy',
      '/Fleury-en-Bière',
      '/Fontaine-Fourches',
      '/Fontaine-le-Port',
      '/Fontainebleau',
      '/Fontains',
      '/Fontenailles',
      '/Fontenay-Trésigny',
      '/Forfry',
      '/Forges',
      '/Fouju',
      '/Fresnes-sur-Marne',
      '/Frétoy',
      '/Fromont',
      '/Fublaines',
      '/Garentreville',
      '/Gastins',
      '/Germigny-l\'Évêque',
      '/Germigny-sous-Coulombs',
      '/Gesvres-le-Chapitre',
      '/Giremoutiers',
      '/Gironville',
      '/Gouaix',
      '/Gouvernes',
      '/Grandpuits-Bailly-Carrois',
      '/Gravon',
      '/Gressy',
      '/Gretz-Armainvilliers',
      '/Grez-sur-Loing',
      '/Grisy-Suisnes',
      '/Grisy-sur-Seine',
      '/Guérard',
      '/Guercheville',
      '/Guermantes',
      '/Guignes',
      '/Gurcy-le-Châtel',
      '/Hautefeuille',
      '/Héricy',
      '/Hermé',
      '/Hondevilliers',
      '/Ichy',
      '/Isles-les-Meldeuses',
      '/Isles-lès-Villenoy',
      '/Iverny',
      '/Jablines',
      '/Jaignes',
      '/Jaulnes',
      '/Jossigny',
      '/Jouarre',
      '/Jouy-le-Châtel',
      '/Jouy-sur-Morin',
      '/Juilly',
      '/Jutigny',
      '/La Brosse-Montceaux',
      '/La Celle-sur-Morin',
      '/La Chapelle-Gauthier',
      '/La Chapelle-Iger',
      '/La Chapelle-la-Reine',
      '/La Chapelle-Moutils',
      '/La Chapelle-Rablais',
      '/La Chapelle-Saint-Sulpice',
      '/La Croix-en-Brie',
      '/La Ferté-Gaucher',
      '/La Ferté-sous-Jouarre',
      '/La Genevraye',
      '/La Grande-Paroisse',
      '/La Haute-Maison',
      '/La Houssaye-en-Brie',
      '/La Madeleine-sur-Loing',
      '/La Rochette',
      '/La Tombe',
      '/La Trétoire',
      '/Lagny-sur-Marne',
      '/Larchant',
      '/Laval-en-Brie',
      '/Le Châtelet-en-Brie',
      '/Le Mée-sur-Seine',
      '/Le Mesnil-Amelot',
      '/Le Pin',
      '/Le Plessis-aux-Bois',
      '/Le Plessis-Feu-Aussoux',
      '/Le Plessis-l\'Évêque',
      '/Le Plessis-Placy',
      '/Le Vaudoué',
      '/Léchelle',
      '/Les Chapelles-Bourbon',
      '/Les Écrennes',
      '/Les Marêts',
      '/Les Ormes-sur-Voulzie',
      '/Lescherolles',
      '/Lesches',
      '/Lésigny',
      '/Leudon-en-Brie',
      '/Lieusaint',
      '/Limoges-Fourches',
      '/Lissy',
      '/Liverdy-en-Brie',
      '/Livry-sur-Seine',
      '/Lizines',
      '/Lizy-sur-Ourcq',
      '/Lognes',
      '/Longperrier',
      '/Longueville',
      '/Lorrez-le-Bocage-Préaux',
      '/Louan-Villegruis-Fontaine',
      '/Luisetaines',
      '/Lumigny-Nesles-Ormeaux',
      '/Luzancy',
      '/Machault',
      '/Magny-le-Hongre',
      '/Maincy',
      '/Maison-Rouge',
      '/Maisoncelles-en-Brie',
      '/Maisoncelles-en-Gâtinais',
      '/Marchémoret',
      '/Marcilly',
      '/Mareuil-lès-Meaux',
      '/Marles-en-Brie',
      '/Marolles-en-Brie',
      '/Marolles-sur-Seine',
      '/Mary-sur-Marne',
      '/Mauperthuis',
      '/Mauregard',
      '/May-en-Multien',
      '/Meaux',
      '/Meigneux',
      '/Meilleray',
      '/Melun',
      '/Melz-sur-Seine',
      '/Méry-sur-Marne',
      '/Messy',
      '/Misy-sur-Yonne',
      '/Mitry-Mory',
      '/Moisenay',
      '/Moissy-Cramayel',
      '/Mondreville',
      '/Mons-en-Montois',
      '/Montceaux-lès-Meaux',
      '/Montceaux-lès-Provins',
      '/Montcourt-Fromonville',
      '/Montdauphin',
      '/Montenils',
      '/Montereau-Fault-Yonne',
      '/Montereau-sur-le-Jard',
      '/Montévrain',
      '/Montgé-en-Goële',
      '/Monthyon',
      '/Montigny-le-Guesdier',
      '/Montigny-Lencoup',
      '/Montigny-sur-Loing',
      '/Montmachoux',
      '/Montolivet',
      '/Montry',
      '/Moret-Loing-et-Orvanne',
      '/Mormant',
      '/Mortcerf',
      '/Mortery',
      '/Mouroux',
      '/Mousseaux-lès-Bray',
      '/Moussy-le-Neuf',
      '/Moussy-le-Vieux',
      '/Mouy-sur-Seine',
      '/Nandy',
      '/Nangis',
      '/Nanteau-sur-Essonne',
      '/Nanteau-sur-Lunain',
      '/Nanteuil-lès-Meaux',
      '/Nanteuil-sur-Marne',
      '/Nantouillet',
      '/Nemours',
      '/Neufmoutiers-en-Brie',
      '/Noisiel',
      '/Noisy-Rudignon',
      '/Noisy-sur-École',
      '/Nonville',
      '/Noyen-sur-Seine',
      '/Obsonville',
      '/Ocquerre',
      '/Oissery',
      '/Orly-sur-Morin',
      '/Ormesson',
      '/Othis',
      '/Ozoir-la-Ferrière',
      '/Ozouer-le-Voulgis',
      '/Paley',
      '/Pamfou',
      '/Paroy',
      '/Passy-sur-Seine',
      '/Pécy',
      '/Penchard',
      '/Perthes',
      '/Pézarches',
      '/Pierre-Levée',
      '/Poigny',
      '/Poincy',
      '/Poligny',
      '/Pommeuse',
      '/Pomponne',
      '/Pontault-Combault',
      '/Pontcarré',
      '/Précy-sur-Marne',
      '/Presles-en-Brie',
      '/Pringy',
      '/Provins',
      '/Puisieux',
      '/Quiers',
      '/Quincy-Voisins',
      '/Rampillon',
      '/Réau',
      '/Rebais',
      '/Recloses',
      '/Remauville',
      '/Reuil-en-Brie',
      '/Roissy-en-Brie',
      '/Rouilly',
      '/Rouvres',
      '/Rozay-en-Brie',
      '/Rubelles',
      '/Rumont',
      '/Rupéreux',
      '/Saâcy-sur-Marne',
      '/Sablonnières',
      '/Saint-Augustin',
      '/Saint-Barthélemy',
      '/Saint-Brice',
      '/Saint-Cyr-sur-Morin',
      '/Saint-Denis-lès-Rebais',
      '/Saint-Fargeau-Ponthierry',
      '/Saint-Fiacre',
      '/Saint-Germain-Laval',
      '/Saint-Germain-Laxis',
      '/Saint-Germain-sous-Doue',
      '/Saint-Germain-sur-École',
      '/Saint-Germain-sur-Morin',
      '/Saint-Hilliers',
      '/Saint-Jean-les-Deux-Jumeaux',
      '/Saint-Just-en-Brie',
      '/Saint-Léger',
      '/Saint-Loup-de-Naud',
      '/Saint-Mammès',
      '/Saint-Mard',
      '/Saint-Mars-Vieux-Maisons',
      '/Saint-Martin-des-Champs',
      '/Saint-Martin-du-Boschet',
      '/Saint-Martin-en-Bière',
      '/Saint-Méry',
      '/Saint-Mesmes',
      '/Saint-Ouen-en-Brie',
      '/Saint-Ouen-sur-Morin',
      '/Saint-Pathus',
      '/Saint-Pierre-lès-Nemours',
      '/Saint-Rémy-la-Vanne',
      '/Saint-Sauveur-lès-Bray',
      '/Saint-Sauveur-sur-École',
      '/Saint-Siméon',
      '/Saint-Soupplets',
      '/Saint-Thibault-des-Vignes',
      '/Sainte-Aulde',
      '/Sainte-Colombe',
      '/Salins',
      '/Sammeron',
      '/Samois-sur-Seine',
      '/Samoreau',
      '/Sancy',
      '/Sancy-lès-Provins',
      '/Savigny-le-Temple',
      '/Savins',
      '/Seine-Port',
      '/Sept-Sorts',
      '/Serris',
      '/Servon',
      '/Signy-Signets',
      '/Sigy',
      '/Sivry-Courtry',
      '/Sognolles-en-Montois',
      '/Soignolles-en-Brie',
      '/Soisy-Bouy',
      '/Solers',
      '/Souppes-sur-Loing',
      '/Sourdun',
      '/Tancrou',
      '/Thénisy',
      '/Thieux',
      '/Thomery',
      '/Thorigny-sur-Marne',
      '/Thoury-Férottes',
      '/Tigeaux',
      '/Torcy',
      '/Touquin',
      '/Tournan-en-Brie',
      '/Tousson',
      '/Treuzy-Levelay',
      '/Trilbardou',
      '/Trilport',
      '/Trocy-en-Multien',
      '/Ury',
      '/Ussy-sur-Marne',
      '/Vaires-sur-Marne',
      '/Valence-en-Brie',
      '/Vanvillé',
      '/Varennes-sur-Seine',
      '/Varreddes',
      '/Vaucourtois',
      '/Vaudoy-en-Brie',
      '/Vaux-le-Pénil',
      '/Vaux-sur-Lunain',
      '/Vendrest',
      '/Verdelot',
      '/Verneuil-l\'Étang',
      '/Vernou-la-Celle-sur-Seine',
      '/Vert-Saint-Denis',
      '/Vieux-Champagne',
      '/Vignely',
      '/Ville-Saint-Jacques',
      '/Villebéon',
      '/Villecerf',
      '/Villemaréchal',
      '/Villemareuil',
      '/Villemer',
      '/Villenauxe-la-Petite',
      '/Villeneuve-le-Comte',
      '/Villeneuve-les-Bordes',
      '/Villeneuve-Saint-Denis',
      '/Villeneuve-sous-Dammartin',
      '/Villeneuve-sur-Bellot',
      '/Villenoy',
      '/Villeparisis',
      '/Villeroy',
      '/Villevaudé',
      '/Villiers-en-Bière',
      '/Villiers-Saint-Georges',
      '/Villiers-sous-Grez',
      '/Villiers-sur-Morin',
      '/Villiers-sur-Seine',
      '/Villuis',
      '/Vimpelles',
      '/Vinantes',
      '/Vincy-Manœuvre',
      '/Voinsles',
      '/Voisenon',
      '/Voulangis',
      '/Voulton',
      '/Voulx',
      '/Vulaines-lès-Provins',
      '/Vulaines-sur-Seine',
      '/Yèbles',
      '/Ablis',
      '/Achères',
      '/Adainville',
      '/Aigremont',
      '/Allainville',
      '/Andelu',
      '/Andrésy',
      '/Arnouville-lès-Mantes',
      '/Aubergenville',
      '/Auffargis',
      '/Auffreville-Brasseuil',
      '/Aulnay-sur-Mauldre',
      '/Auteuil',
      '/Autouillet',
      '/Bailly',
      '/Bazainville',
      '/Bazemont',
      '/Bazoches-sur-Guyonne',
      '/Béhoust',
      '/Bennecourt',
      '/Beynes',
      '/Blaru',
      '/Boinville-en-Mantois',
      '/Boinville-le-Gaillard',
      '/Boinvilliers',
      '/Bois-d\'Arcy',
      '/Boissets',
      '/Boissy-Mauvoisin',
      '/Boissy-sans-Avoir',
      '/Bonnelles',
      '/Bonnières-sur-Seine',
      '/Bouafle',
      '/Bougival',
      '/Bourdonné',
      '/Breuil-Bois-Robert',
      '/Bréval',
      '/Brueil-en-Vexin',
      '/Buc',
      '/Buchelay',
      '/Bullion',
      '/Carrières-sous-Poissy',
      '/Carrières-sur-Seine',
      '/Cernay-la-Ville',
      '/Chambourcy',
      '/Chanteloup-les-Vignes',
      '/Chapet',
      '/Châteaufort',
      '/Chatou',
      '/Chaufour-lès-Bonnières',
      '/Chavenay',
      '/Chevreuse',
      '/Choisel',
      '/Civry-la-Forêt',
      '/Clairefontaine-en-Yvelines',
      '/Coignières',
      '/Condé-sur-Vesgre',
      '/Conflans-Sainte-Honorine',
      '/Courgent',
      '/Cravent',
      '/Crespières',
      '/Croissy-sur-Seine',
      '/Dammartin-en-Serve',
      '/Dampierre-en-Yvelines',
      '/Dannemarie',
      '/Davron',
      '/Drocourt',
      '/Ecquevilly',
      '/Élancourt',
      '/Émancé',
      '/Épône',
      '/Évecquemont',
      '/Favrieux',
      '/Feucherolles',
      '/Flacourt',
      '/Flexanville',
      '/Flins-Neuve-Église',
      '/Flins-sur-Seine',
      '/Follainville-Dennemont',
      '/Fontenay-le-Fleury',
      '/Fontenay-Mauvoisin',
      '/Fontenay-Saint-Père',
      '/Freneuse',
      '/Gaillon-sur-Montcient',
      '/Galluis',
      '/Gambais',
      '/Gambaiseuil',
      '/Garancières',
      '/Gargenville',
      '/Gazeran',
      '/Gommecourt',
      '/Goupillières',
      '/Goussonville',
      '/Grandchamp',
      '/Gressey',
      '/Grosrouvre',
      '/Guernes',
      '/Guerville',
      '/Guitrancourt',
      '/Guyancourt',
      '/Hardricourt',
      '/Hargeville',
      '/Herbeville',
      '/Hermeray',
      '/Houdan',
      '/Houilles',
      '/Issou',
      '/Jambville',
      '/Jouars-Pontchartrain',
      '/Jouy-en-Josas',
      '/Jouy-Mauvoisin',
      '/Jumeauville',
      '/Juziers',
      '/L\'Étang-la-Ville',
      '/La Boissière-École',
      '/La Celle-les-Bordes',
      '/La Celle-Saint-Cloud',
      '/La Falaise',
      '/La Hauteville',
      '/La Queue-les-Yvelines',
      '/La Verrière',
      '/La Villeneuve-en-Chevrie',
      '/Lainville-en-Vexin',
      '/Le Chesnay-Rocquencourt',
      '/Le Mesnil-le-Roi',
      '/Le Mesnil-Saint-Denis',
      '/Le Pecq',
      '/Le Perray-en-Yvelines',
      '/Le Port-Marly',
      '/Le Tartre-Gaudran',
      '/Le Tertre-Saint-Denis',
      '/Le Tremblay-sur-Mauldre',
      '/Le Vésinet',
      '/Les Alluets-le-Roi',
      '/Les Bréviaires',
      '/Les Clayes-sous-Bois',
      '/Les Essarts-le-Roi',
      '/Les Loges-en-Josas',
      '/Les Mesnuls',
      '/Les Mureaux',
      '/Lévis-Saint-Nom',
      '/Limay',
      '/Limetz-Villez',
      '/Lommoye',
      '/Longnes',
      '/Longvilliers',
      '/Louveciennes',
      '/Magnanville',
      '/Magny-les-Hameaux',
      '/Maisons-Laffitte',
      '/Mantes-la-Jolie',
      '/Mantes-la-Ville',
      '/Marcq',
      '/Mareil-le-Guyon',
      '/Mareil-Marly',
      '/Mareil-sur-Mauldre',
      '/Marly-le-Roi',
      '/Maule',
      '/Maulette',
      '/Maurecourt',
      '/Maurepas',
      '/Médan',
      '/Ménerville',
      '/Méré',
      '/Méricourt',
      '/Meulan-en-Yvelines',
      '/Mézières-sur-Seine',
      '/Mézy-sur-Seine',
      '/Millemont',
      '/Milon-la-Chapelle',
      '/Mittainville',
      '/Moisson',
      '/Mondreville',
      '/Montainville',
      '/Montalet-le-Bois',
      '/Montchauvet',
      '/Montesson',
      '/Montfort-l\'Amaury',
      '/Montigny-le-Bretonneux',
      '/Morainvilliers',
      '/Mousseaux-sur-Seine',
      '/Mulcent',
      '/Neauphle-le-Château',
      '/Neauphle-le-Vieux',
      '/Neauphlette',
      '/Nézel',
      '/Noisy-le-Roi',
      '/Notre-Dame-de-la-Mer',
      '/Oinville-sur-Montcient',
      '/Orcemont',
      '/Orgerus',
      '/Orgeval',
      '/Orphin',
      '/Orsonville',
      '/Orvilliers',
      '/Osmoy',
      '/Paray-Douaville',
      '/Perdreauville',
      '/Plaisir',
      '/Poigny-la-Forêt',
      '/Poissy',
      '/Ponthévrard',
      '/Porcheville',
      '/Prunay-en-Yvelines',
      '/Prunay-le-Temple',
      '/Raizeux',
      '/Rambouillet',
      '/Rennemoulin',
      '/Richebourg',
      '/Rochefort-en-Yvelines',
      '/Rolleboise',
      '/Rosay',
      '/Rosny-sur-Seine',
      '/Sailly',
      '/Saint-Arnoult-en-Yvelines',
      '/Saint-Cyr-l\'École',
      '/Saint-Forget',
      '/Saint-Germain-de-la-Grange',
      '/Saint-Germain-en-Laye',
      '/Saint-Hilarion',
      '/Saint-Illiers-la-Ville',
      '/Saint-Illiers-le-Bois',
      '/Saint-Lambert',
      '/Saint-Léger-en-Yvelines',
      '/Saint-Martin-de-Bréthencourt',
      '/Saint-Martin-des-Champs',
      '/Saint-Martin-la-Garenne',
      '/Saint-Nom-la-Bretèche',
      '/Saint-Rémy-l\'Honoré',
      '/Saint-Rémy-lès-Chevreuse',
      '/Sainte-Mesme',
      '/Sartrouville',
      '/Saulx-Marchais',
      '/Senlisse',
      '/Septeuil',
      '/Soindres',
      '/Sonchamp',
      '/Tacoignières',
      '/Tessancourt-sur-Aubette',
      '/Thiverval-Grignon',
      '/Thoiry',
      '/Tilly',
      '/Toussus-le-Noble',
      '/Trappes',
      '/Triel-sur-Seine',
      '/Vaux-sur-Seine',
      '/Vélizy-Villacoublay',
      '/Verneuil-sur-Seine',
      '/Vernouillet',
      '/Versailles',
      '/Vert',
      '/Vicq',
      '/Vieille-Église-en-Yvelines',
      '/Villennes-sur-Seine',
      '/Villepreux',
      '/Villette',
      '/Villiers-le-Mahieu',
      '/Villiers-Saint-Frédéric',
      '/Viroflay',
      '/Voisins-le-Bretonneux',
      '/Abbéville-la-Rivière',
      '/Angerville',
      '/Angervilliers',
      '/Arpajon',
      '/Arrancourt',
      '/Athis-Mons',
      '/Authon-la-Plaine',
      '/Auvernaux',
      '/Auvers-Saint-Georges',
      '/Avrainville',
      '/Ballainvilliers',
      '/Ballancourt-sur-Essonne',
      '/Baulne',
      '/Bièvres',
      '/Blandy',
      '/Boigneville',
      '/Bois-Herpin',
      '/Boissy-la-Rivière',
      '/Boissy-le-Cutté',
      '/Boissy-le-Sec',
      '/Boissy-sous-Saint-Yon',
      '/Bondoufle',
      '/Boullay-les-Troux',
      '/Bouray-sur-Juine',
      '/Boussy-Saint-Antoine',
      '/Boutervilliers',
      '/Boutigny-sur-Essonne',
      '/Bouville',
      '/Brétigny-sur-Orge',
      '/Breuillet',
      '/Breux-Jouy',
      '/Brières-les-Scellés',
      '/Briis-sous-Forges',
      '/Brouy',
      '/Brunoy',
      '/Bruyères-le-Châtel',
      '/Buno-Bonnevaux',
      '/Bures-sur-Yvette',
      '/Cerny',
      '/Chalo-Saint-Mars',
      '/Chalou-Moulineux',
      '/Chamarande',
      '/Champcueil',
      '/Champlan',
      '/Champmotteux',
      '/Chatignonville',
      '/Chauffour-lès-Étréchy',
      '/Cheptainville',
      '/Chevannes',
      '/Chilly-Mazarin',
      '/Congerville-Thionville',
      '/Corbeil-Essonnes',
      '/Corbreuse',
      '/Courances',
      '/Courdimanche-sur-Essonne',
      '/Courson-Monteloup',
      '/Crosne',
      '/D\'Huison-Longueville',
      '/Dannemois',
      '/Dourdan',
      '/Draveil',
      '/Écharcon',
      '/Égly',
      '/Épinay-sous-Sénart',
      '/Épinay-sur-Orge',
      '/Étampes',
      '/Étiolles',
      '/Étréchy',
      '/Évry-Courcouronnes',
      '/Fleury-Mérogis',
      '/Fontaine-la-Rivière',
      '/Fontenay-le-Vicomte',
      '/Fontenay-lès-Briis',
      '/Forges-les-Bains',
      '/Gif-sur-Yvette',
      '/Gironville-sur-Essonne',
      '/Gometz-la-Ville',
      '/Gometz-le-Châtel',
      '/Grigny',
      '/Guibeville',
      '/Guigneville-sur-Essonne',
      '/Guillerval',
      '/Igny',
      '/Itteville',
      '/Janville-sur-Juine',
      '/Janvry',
      '/Juvisy-sur-Orge',
      '/La Ferté-Alais',
      '/La Forêt-le-Roi',
      '/La Forêt-Sainte-Croix',
      '/La Norville',
      '/La Ville-du-Bois',
      '/Lardy',
      '/Le Coudray-Montceaux',
      '/Le Mérévillois',
      '/Le Plessis-Pâté',
      '/Le Val-Saint-Germain',
      '/Les Granges-le-Roi',
      '/Les Molières',
      '/Les Ulis',
      '/Leudeville',
      '/Leuville-sur-Orge',
      '/Limours',
      '/Linas',
      '/Lisses',
      '/Longjumeau',
      '/Longpont-sur-Orge',
      '/Maisse',
      '/Marcoussis',
      '/Marolles-en-Beauce',
      '/Marolles-en-Hurepoix',
      '/Massy',
      '/Mauchamps',
      '/Mennecy',
      '/Mérobert',
      '/Mespuits',
      '/Milly-la-Forêt',
      '/Moigny-sur-École',
      '/Mondeville',
      '/Monnerville',
      '/Montgeron',
      '/Montlhéry',
      '/Morangis',
      '/Morigny-Champigny',
      '/Morsang-sur-Orge',
      '/Morsang-sur-Seine',
      '/Nainville-les-Roches',
      '/Nozay',
      '/Ollainville',
      '/Oncy-sur-École',
      '/Ormoy',
      '/Ormoy-la-Rivière',
      '/Orsay',
      '/Orveau',
      '/Palaiseau',
      '/Paray-Vieille-Poste',
      '/Pecqueuse',
      '/Plessis-Saint-Benoist',
      '/Prunay-sur-Essonne',
      '/Puiselet-le-Marais',
      '/Pussay',
      '/Quincy-sous-Sénart',
      '/Richarville',
      '/Ris-Orangis',
      '/Roinville',
      '/Roinvilliers',
      '/Saclas',
      '/Saclay',
      '/Saint-Aubin',
      '/Saint-Chéron',
      '/Saint-Cyr-la-Rivière',
      '/Saint-Cyr-sous-Dourdan',
      '/Saint-Escobille',
      '/Saint-Germain-lès-Arpajon',
      '/Saint-Germain-lès-Corbeil',
      '/Saint-Hilaire',
      '/Saint-Jean-de-Beauregard',
      '/Saint-Maurice-Montcouronne',
      '/Saint-Michel-sur-Orge',
      '/Saint-Pierre-du-Perray',
      '/Saint-Sulpice-de-Favières',
      '/Saint-Vrain',
      '/Saint-Yon',
      '/Sainte-Geneviève-des-Bois',
      '/Saintry-sur-Seine',
      '/Saulx-les-Chartreux',
      '/Savigny-sur-Orge',
      '/Sermaise',
      '/Soisy-sur-École',
      '/Soisy-sur-Seine',
      '/Souzy-la-Briche',
      '/Tigery',
      '/Torfou',
      '/Valpuiseaux',
      '/Varennes-Jarcy',
      '/Vaugrigneuse',
      '/Vauhallan',
      '/Vayres-sur-Essonne',
      '/Verrières-le-Buisson',
      '/Vert-le-Grand',
      '/Vert-le-Petit',
      '/Videlles',
      '/Vigneux-sur-Seine',
      '/Villabé',
      '/Villebon-sur-Yvette',
      '/Villeconin',
      '/Villejust',
      '/Villemoisson-sur-Orge',
      '/Villeneuve-sur-Auvers',
      '/Villiers-le-Bâcle',
      '/Villiers-sur-Orge',
      '/Viry-Châtillon',
      '/Wissous',
      '/Yerres',
      '/Antony',
      '/Asnières-sur-Seine',
      '/Bagneux',
      '/Bois-Colombes',
      '/Boulogne-Billancourt',
      '/Bourg-la-Reine',
      '/Châtenay-Malabry',
      '/Châtillon',
      '/Chaville',
      '/Clamart',
      '/Clichy',
      '/Colombes',
      '/Courbevoie',
      '/Fontenay-aux-Roses',
      '/Garches',
      '/Gennevilliers',
      '/Issy-les-Moulineaux',
      '/La Garenne-Colombes',
      '/Le Plessis-Robinson',
      '/Levallois-Perret',
      '/Malakoff',
      '/Marnes-la-Coquette',
      '/Meudon',
      '/Montrouge',
      '/Nanterre',
      '/Neuilly-sur-Seine',
      '/Puteaux',
      '/Rueil-Malmaison',
      '/Saint-Cloud',
      '/Sceaux',
      '/Sèvres',
      '/Suresnes',
      '/Vanves',
      '/Vaucresson',
      '/Ville-d\'Avray',
      '/Villeneuve-la-Garenne',
      '/Aubervilliers',
      '/Aulnay-sous-Bois',
      '/Bagnolet',
      '/Bobigny',
      '/Bondy',
      '/Clichy-sous-Bois',
      '/Coubron',
      '/Drancy',
      '/Dugny',
      '/Épinay-sur-Seine',
      '/Gagny',
      '/Gournay-sur-Marne',
      '/L\'Île-Saint-Denis',
      '/La Courneuve',
      '/Le Blanc-Mesnil',
      '/Le Bourget',
      '/Le Pré-Saint-Gervais',
      '/Le Raincy',
      '/Les Lilas',
      '/Les Pavillons-sous-Bois',
      '/Livry-Gargan',
      '/Montfermeil',
      '/Montreuil',
      '/Neuilly-Plaisance',
      '/Neuilly-sur-Marne',
      '/Noisy-le-Grand',
      '/Noisy-le-Sec',
      '/Pantin',
      '/Pierrefitte-sur-Seine',
      '/Romainville',
      '/Rosny-sous-Bois',
      '/Saint-Denis',
      '/Saint-Ouen-sur-Seine',
      '/Sevran',
      '/Stains',
      '/Tremblay-en-France',
      '/Vaujours',
      '/Villemomble',
      '/Villepinte',
      '/Villetaneuse',
      '/Ablon-sur-Seine',
      '/Alfortville',
      '/Arcueil',
      '/Boissy-Saint-Léger',
      '/Bonneuil-sur-Marne',
      '/Bry-sur-Marne',
      '/Cachan',
      '/Champigny-sur-Marne',
      '/Charenton-le-Pont',
      '/Chennevières-sur-Marne',
      '/Chevilly-Larue',
      '/Choisy-le-Roi',
      '/Créteil',
      '/Fontenay-sous-Bois',
      '/Fresnes',
      '/Gentilly',
      '/Ivry-sur-Seine',
      '/Joinville-le-Pont',
      '/L\'Haÿ-les-Roses',
      '/La Queue-en-Brie',
      '/Le Kremlin-Bicêtre',
      '/Le Perreux-sur-Marne',
      '/Le Plessis-Trévise',
      '/Limeil-Brévannes',
      '/Maisons-Alfort',
      '/Mandres-les-Roses',
      '/Marolles-en-Brie',
      '/Nogent-sur-Marne',
      '/Noiseau',
      '/Orly',
      '/Ormesson-sur-Marne',
      '/Périgny',
      '/Rungis',
      '/Saint-Mandé',
      '/Saint-Maur-des-Fossés',
      '/Saint-Maurice',
      '/Santeny',
      '/Sucy-en-Brie',
      '/Thiais',
      '/Valenton',
      '/Villecresnes',
      '/Villejuif',
      '/Villeneuve-le-Roi',
      '/Villeneuve-Saint-Georges',
      '/Villiers-sur-Marne',
      '/Vincennes',
      '/Vitry-sur-Seine'
    ]
  }
}
